# Generated by Django 6.0.1 on 2026-01-23 02:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Startup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('stage', models.CharField(choices=[('idea', 'Idea'), ('mvp', 'MVP'), ('seed', 'Seed'), ('growth', 'Growth'), ('scale', 'Scale')], max_length=20)),
                ('team_size', models.PositiveIntegerField()),
                ('funding', models.CharField(blank=True, max_length=100)),
                ('website', models.URLField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='startup_logos/')),
                ('founded_date', models.DateField()),
                ('location', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='StartupContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='startups.startup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StartupProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('company_website', models.URLField(blank=True)),
                ('founded_year', models.IntegerField()),
                ('industry', models.CharField(choices=[('fintech', 'FinTech'), ('healthtech', 'HealthTech'), ('edtech', 'EdTech'), ('agritech', 'AgriTech'), ('ecommerce', 'E-commerce'), ('saas', 'SaaS'), ('other', 'Other')], max_length=20)),
                ('stage', models.CharField(choices=[('idea', 'Idea Stage'), ('mvp', 'MVP/Prototype'), ('early', 'Early Stage'), ('growth', 'Growth Stage'), ('scale', 'Scaling')], max_length=20)),
                ('team_size', models.CharField(choices=[('1-5', '1-5 members'), ('6-10', '6-10 members'), ('11-25', '11-25 members'), ('26-50', '26-50 members'), ('50+', '50+ members')], max_length=20)),
                ('funding_stage', models.CharField(choices=[('bootstrapped', 'Bootstrapped'), ('pre-seed', 'Pre-Seed'), ('seed', 'Seed'), ('series-a', 'Series A'), ('series-b+', 'Series B+')], max_length=20)),
                ('product_description', models.TextField()),
                ('target_market', models.TextField()),
                ('revenue_model', models.TextField()),
                ('current_revenue', models.CharField(blank=True, max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='startup_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
