# Generated by Django 6.0.1 on 2026-01-24 20:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='startup',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='startup',
            name='contact_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='startup',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='startup',
            name='crunchbase_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='last_funding_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='last_funding_round',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='startup',
            name='linkedin_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='startup',
            name='total_funding',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total funding raised in USD', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='twitter_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='views_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='startup',
            index=models.Index(fields=['is_active'], name='startups_st_is_acti_9f57d2_idx'),
        ),
        migrations.AddIndex(
            model_name='startup',
            index=models.Index(fields=['stage'], name='startups_st_stage_120209_idx'),
        ),
        migrations.AddIndex(
            model_name='startup',
            index=models.Index(fields=['category'], name='startups_st_categor_f44471_idx'),
        ),
    ]
