# Generated by Django 6.0.1 on 2026-01-26 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0002_alter_startup_options_startup_contact_count_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='startupcontact',
            options={'ordering': ['-created_at']},
        ),
    ]
