# Generated by Django 6.0.1 on 2026-01-23 02:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivityStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posts_count', models.IntegerField(default=0)),
                ('comments_count', models.IntegerField(default=0)),
                ('helps_count', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='activity_stats', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_notifications', models.BooleanField(default=True)),
                ('community_updates', models.BooleanField(default=True)),
                ('job_alerts', models.BooleanField(default=True)),
                ('event_reminders', models.BooleanField(default=True)),
                ('profile_visibility', models.BooleanField(default=True)),
                ('show_activity_status', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Achievement Title')),
                ('description', models.TextField(help_text='What the user did to earn this achievement', verbose_name='Description')),
                ('achievement_type', models.CharField(choices=[('engagement', 'Engagement'), ('content', 'Content Creation'), ('social', 'Social Interaction'), ('milestone', 'Milestone'), ('expertise', 'Expertise'), ('streak', 'Streak'), ('special', 'Special')], default='engagement', max_length=50, verbose_name='Type')),
                ('badge_level', models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum'), ('diamond', 'Diamond')], default='bronze', max_length=20, verbose_name='Badge Level')),
                ('badge_icon', models.ImageField(blank=True, help_text='Icon for the achievement badge', null=True, upload_to='badge_icons/', verbose_name='Badge Icon')),
                ('points_awarded', models.PositiveIntegerField(default=0, verbose_name='Points Awarded')),
                ('earned_at', models.DateTimeField(auto_now_add=True, verbose_name='Earned At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Achievement',
                'verbose_name_plural': 'Achievements',
                'ordering': ['-earned_at'],
                'indexes': [models.Index(fields=['user', 'earned_at'], name='leaderboard_user_id_3e6cd7_idx'), models.Index(fields=['achievement_type'], name='leaderboard_achieve_483e62_idx'), models.Index(fields=['badge_level'], name='leaderboard_badge_l_448066_idx')],
                'unique_together': {('user', 'title')},
            },
        ),
        migrations.CreateModel(
            name='PointTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(help_text='Positive for earned, negative for spent', verbose_name='Points')),
                ('action_type', models.CharField(choices=[('post_created', 'Post Created'), ('comment_added', 'Comment Added'), ('post_liked', 'Post Liked'), ('achievement_earned', 'Achievement Earned'), ('daily_login', 'Daily Login'), ('profile_completed', 'Profile Completed'), ('content_shared', 'Content Shared'), ('review_added', 'Review Added'), ('service_created', 'Service Created'), ('startup_created', 'Startup Created'), ('referral', 'Referral'), ('purchase', 'Purchase'), ('reward_redeemed', 'Reward Redeemed'), ('penalty', 'Penalty'), ('other', 'Other')], max_length=50, verbose_name='Action Type')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Related Object ID')),
                ('description', models.CharField(help_text='Brief description of the transaction', max_length=255, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Transaction Date')),
                ('expires_at', models.DateTimeField(blank=True, help_text='When these points expire (if applicable)', null=True, verbose_name='Expires At')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name='Related Content Type')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_transactions', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Point Transaction',
                'verbose_name_plural': 'Point Transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='leaderboard_user_id_585d3c_idx'), models.Index(fields=['action_type'], name='leaderboard_action__a10d81_idx'), models.Index(fields=['expires_at'], name='leaderboard_expires_db5bab_idx')],
            },
        ),
    ]
