# Generated by Django 6.0.1 on 2026-01-24 20:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useractivitystats',
            options={'verbose_name': 'User Activity Stats', 'verbose_name_plural': 'User Activity Stats'},
        ),
        migrations.AddField(
            model_name='useractivitystats',
            name='achievements_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='useractivitystats',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='useractivitystats',
            name='last_activity_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='useractivitystats',
            name='points_last_month',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='useractivitystats',
            name='points_last_week',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='useractivitystats',
            name='total_points',
            field=models.IntegerField(default=0),
        ),
    ]
