# Generated by Django 6.0.1 on 2026-01-27 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0002_alter_useractivitystats_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pointtransaction',
            name='content_type',
        ),
    ]
