# Generated by Django 6.0.1 on 2026-01-28 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupchatmessage',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='groupchatmessage',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='group_chat_files/'),
        ),
        migrations.AddField(
            model_name='groupchatmessage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='group_chat_images/'),
        ),
    ]
