# Generated by Django 5.2.5 on 2026-01-17 20:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CofounderProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startup_name', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=100)),
                ('equity_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('years_with_startup', models.IntegerField()),
                ('expertise', models.TextField()),
                ('product_description', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cofounder_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CTOProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_company', models.CharField(max_length=200)),
                ('current_role', models.CharField(max_length=100)),
                ('tech_stack', models.TextField()),
                ('team_lead_experience', models.CharField(choices=[('1-5', '1-5 developers'), ('6-15', '6-15 developers'), ('16-30', '16-30 developers'), ('30+', '30+ developers')], max_length=10)),
                ('projects_led', models.TextField()),
                ('technical_expertise', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cto_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IncubatorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=200)),
                ('organization_website', models.URLField()),
                ('year_established', models.IntegerField()),
                ('program_type', models.CharField(choices=[('incubator', 'Incubator'), ('accelerator', 'Accelerator'), ('both', 'Both'), ('innovation-hub', 'Innovation Hub')], max_length=20)),
                ('startups_supported', models.IntegerField()),
                ('support_services', models.TextField()),
                ('success_stories', models.TextField(blank=True)),
                ('application_process', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='incubator_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InvestorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investor_type', models.CharField(choices=[('angel', 'Angel Investor'), ('vc', 'Venture Capital'), ('corporate', 'Corporate Investor'), ('family-office', 'Family Office')], max_length=20)),
                ('investment_range', models.CharField(max_length=50)),
                ('focus_sectors', models.TextField()),
                ('previous_investments', models.TextField(blank=True)),
                ('portfolio_size', models.CharField(blank=True, max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='investor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MemberProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession', models.CharField(max_length=200)),
                ('skills', models.TextField()),
                ('interests', models.TextField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RevOpsProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_company', models.CharField(max_length=200)),
                ('current_role', models.CharField(max_length=100)),
                ('years_experience', models.CharField(choices=[('0-2', '0-2 years'), ('3-5', '3-5 years'), ('6-10', '6-10 years'), ('10+', '10+ years')], max_length=10)),
                ('tools_expertise', models.TextField()),
                ('specializations', models.TextField()),
                ('achievements', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='revops_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StartupProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('company_website', models.URLField(blank=True)),
                ('founded_year', models.IntegerField()),
                ('industry', models.CharField(choices=[('fintech', 'FinTech'), ('healthtech', 'HealthTech'), ('edtech', 'EdTech'), ('agritech', 'AgriTech'), ('ecommerce', 'E-commerce'), ('saas', 'SaaS'), ('other', 'Other')], max_length=20)),
                ('stage', models.CharField(choices=[('idea', 'Idea Stage'), ('mvp', 'MVP/Prototype'), ('early', 'Early Stage'), ('growth', 'Growth Stage'), ('scale', 'Scaling')], max_length=20)),
                ('team_size', models.CharField(choices=[('1-5', '1-5 members'), ('6-10', '6-10 members'), ('11-25', '11-25 members'), ('26-50', '26-50 members'), ('50+', '50+ members')], max_length=20)),
                ('funding_stage', models.CharField(choices=[('bootstrapped', 'Bootstrapped'), ('pre-seed', 'Pre-Seed'), ('seed', 'Seed'), ('series-a', 'Series A'), ('series-b+', 'Series B+')], max_length=20)),
                ('product_description', models.TextField()),
                ('target_market', models.TextField()),
                ('revenue_model', models.TextField()),
                ('current_revenue', models.CharField(blank=True, max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='startup_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('member', 'Community Member'), ('investor', 'Investor'), ('startup', 'Startup/Founder'), ('cofounder', 'Co-Founder'), ('incubator', 'Startup Incubator'), ('revops', 'Revenue Operations'), ('cto', 'CTO/Technical Lead')], max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
