# Generated by Django 5.2.5 on 2026-01-18 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
