# Generated by Django 6.0.1 on 2026-01-27 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0003_alter_userprofile_bio_alter_userprofile_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='investorprofile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
